package com.google.protobuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gogoproto/gogo.proto

public final class GoGoProtos {
  private GoGoProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(goprotoEnumPrefix);
    registry.add(goprotoEnumStringer);
    registry.add(enumStringer);
    registry.add(enumCustomname);
    registry.add(enumdecl);
    registry.add(enumvalueCustomname);
    registry.add(goprotoGettersAll);
    registry.add(goprotoEnumPrefixAll);
    registry.add(goprotoStringerAll);
    registry.add(verboseEqualAll);
    registry.add(faceAll);
    registry.add(gostringAll);
    registry.add(populateAll);
    registry.add(stringerAll);
    registry.add(onlyoneAll);
    registry.add(equalAll);
    registry.add(descriptionAll);
    registry.add(testgenAll);
    registry.add(benchgenAll);
    registry.add(marshalerAll);
    registry.add(unmarshalerAll);
    registry.add(stableMarshalerAll);
    registry.add(sizerAll);
    registry.add(goprotoEnumStringerAll);
    registry.add(enumStringerAll);
    registry.add(unsafeMarshalerAll);
    registry.add(unsafeUnmarshalerAll);
    registry.add(goprotoExtensionsMapAll);
    registry.add(goprotoUnrecognizedAll);
    registry.add(gogoprotoImport);
    registry.add(protosizerAll);
    registry.add(compareAll);
    registry.add(typedeclAll);
    registry.add(enumdeclAll);
    registry.add(goprotoGetters);
    registry.add(goprotoStringer);
    registry.add(verboseEqual);
    registry.add(face);
    registry.add(gostring);
    registry.add(populate);
    registry.add(stringer);
    registry.add(onlyone);
    registry.add(equal);
    registry.add(description);
    registry.add(testgen);
    registry.add(benchgen);
    registry.add(marshaler);
    registry.add(unmarshaler);
    registry.add(stableMarshaler);
    registry.add(sizer);
    registry.add(unsafeMarshaler);
    registry.add(unsafeUnmarshaler);
    registry.add(goprotoExtensionsMap);
    registry.add(goprotoUnrecognized);
    registry.add(protosizer);
    registry.add(compare);
    registry.add(typedecl);
    registry.add(nullable);
    registry.add(embed);
    registry.add(customtype);
    registry.add(customname);
    registry.add(jsontag);
    registry.add(moretags);
    registry.add(casttype);
    registry.add(castkey);
    registry.add(castvalue);
    registry.add(stdtime);
    registry.add(stdduration);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int GOPROTO_ENUM_PREFIX_FIELD_NUMBER = 62001;
  /**
   * <code>extend .google.protobuf.EnumOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumOptions,
      Boolean> goprotoEnumPrefix = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int GOPROTO_ENUM_STRINGER_FIELD_NUMBER = 62021;
  /**
   * <code>extend .google.protobuf.EnumOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumOptions,
      Boolean> goprotoEnumStringer = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int ENUM_STRINGER_FIELD_NUMBER = 62022;
  /**
   * <code>extend .google.protobuf.EnumOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumOptions,
      Boolean> enumStringer = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int ENUM_CUSTOMNAME_FIELD_NUMBER = 62023;
  /**
   * <code>extend .google.protobuf.EnumOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumOptions,
      String> enumCustomname = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        String.class,
        null);
  public static final int ENUMDECL_FIELD_NUMBER = 62024;
  /**
   * <code>extend .google.protobuf.EnumOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumOptions,
      Boolean> enumdecl = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int ENUMVALUE_CUSTOMNAME_FIELD_NUMBER = 66001;
  /**
   * <code>extend .google.protobuf.EnumValueOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumValueOptions,
      String> enumvalueCustomname = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        String.class,
        null);
  public static final int GOPROTO_GETTERS_ALL_FIELD_NUMBER = 63001;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      Boolean> goprotoGettersAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int GOPROTO_ENUM_PREFIX_ALL_FIELD_NUMBER = 63002;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      Boolean> goprotoEnumPrefixAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int GOPROTO_STRINGER_ALL_FIELD_NUMBER = 63003;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      Boolean> goprotoStringerAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int VERBOSE_EQUAL_ALL_FIELD_NUMBER = 63004;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      Boolean> verboseEqualAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int FACE_ALL_FIELD_NUMBER = 63005;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      Boolean> faceAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int GOSTRING_ALL_FIELD_NUMBER = 63006;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      Boolean> gostringAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int POPULATE_ALL_FIELD_NUMBER = 63007;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      Boolean> populateAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int STRINGER_ALL_FIELD_NUMBER = 63008;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      Boolean> stringerAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int ONLYONE_ALL_FIELD_NUMBER = 63009;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      Boolean> onlyoneAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int EQUAL_ALL_FIELD_NUMBER = 63013;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      Boolean> equalAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int DESCRIPTION_ALL_FIELD_NUMBER = 63014;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      Boolean> descriptionAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int TESTGEN_ALL_FIELD_NUMBER = 63015;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      Boolean> testgenAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int BENCHGEN_ALL_FIELD_NUMBER = 63016;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      Boolean> benchgenAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int MARSHALER_ALL_FIELD_NUMBER = 63017;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      Boolean> marshalerAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int UNMARSHALER_ALL_FIELD_NUMBER = 63018;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      Boolean> unmarshalerAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int STABLE_MARSHALER_ALL_FIELD_NUMBER = 63019;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      Boolean> stableMarshalerAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int SIZER_ALL_FIELD_NUMBER = 63020;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      Boolean> sizerAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int GOPROTO_ENUM_STRINGER_ALL_FIELD_NUMBER = 63021;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      Boolean> goprotoEnumStringerAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int ENUM_STRINGER_ALL_FIELD_NUMBER = 63022;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      Boolean> enumStringerAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int UNSAFE_MARSHALER_ALL_FIELD_NUMBER = 63023;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      Boolean> unsafeMarshalerAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int UNSAFE_UNMARSHALER_ALL_FIELD_NUMBER = 63024;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      Boolean> unsafeUnmarshalerAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int GOPROTO_EXTENSIONS_MAP_ALL_FIELD_NUMBER = 63025;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      Boolean> goprotoExtensionsMapAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int GOPROTO_UNRECOGNIZED_ALL_FIELD_NUMBER = 63026;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      Boolean> goprotoUnrecognizedAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int GOGOPROTO_IMPORT_FIELD_NUMBER = 63027;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      Boolean> gogoprotoImport = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int PROTOSIZER_ALL_FIELD_NUMBER = 63028;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      Boolean> protosizerAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int COMPARE_ALL_FIELD_NUMBER = 63029;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      Boolean> compareAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int TYPEDECL_ALL_FIELD_NUMBER = 63030;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      Boolean> typedeclAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int ENUMDECL_ALL_FIELD_NUMBER = 63031;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      Boolean> enumdeclAll = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int GOPROTO_GETTERS_FIELD_NUMBER = 64001;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      Boolean> goprotoGetters = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int GOPROTO_STRINGER_FIELD_NUMBER = 64003;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      Boolean> goprotoStringer = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int VERBOSE_EQUAL_FIELD_NUMBER = 64004;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      Boolean> verboseEqual = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int FACE_FIELD_NUMBER = 64005;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      Boolean> face = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int GOSTRING_FIELD_NUMBER = 64006;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      Boolean> gostring = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int POPULATE_FIELD_NUMBER = 64007;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      Boolean> populate = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int STRINGER_FIELD_NUMBER = 67008;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      Boolean> stringer = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int ONLYONE_FIELD_NUMBER = 64009;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      Boolean> onlyone = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int EQUAL_FIELD_NUMBER = 64013;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      Boolean> equal = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int DESCRIPTION_FIELD_NUMBER = 64014;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      Boolean> description = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int TESTGEN_FIELD_NUMBER = 64015;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      Boolean> testgen = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int BENCHGEN_FIELD_NUMBER = 64016;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      Boolean> benchgen = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int MARSHALER_FIELD_NUMBER = 64017;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      Boolean> marshaler = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int UNMARSHALER_FIELD_NUMBER = 64018;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      Boolean> unmarshaler = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int STABLE_MARSHALER_FIELD_NUMBER = 64019;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      Boolean> stableMarshaler = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int SIZER_FIELD_NUMBER = 64020;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      Boolean> sizer = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int UNSAFE_MARSHALER_FIELD_NUMBER = 64023;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      Boolean> unsafeMarshaler = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int UNSAFE_UNMARSHALER_FIELD_NUMBER = 64024;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      Boolean> unsafeUnmarshaler = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int GOPROTO_EXTENSIONS_MAP_FIELD_NUMBER = 64025;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      Boolean> goprotoExtensionsMap = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int GOPROTO_UNRECOGNIZED_FIELD_NUMBER = 64026;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      Boolean> goprotoUnrecognized = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int PROTOSIZER_FIELD_NUMBER = 64028;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      Boolean> protosizer = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int COMPARE_FIELD_NUMBER = 64029;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      Boolean> compare = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int TYPEDECL_FIELD_NUMBER = 64030;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      Boolean> typedecl = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int NULLABLE_FIELD_NUMBER = 65001;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      Boolean> nullable = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int EMBED_FIELD_NUMBER = 65002;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      Boolean> embed = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int CUSTOMTYPE_FIELD_NUMBER = 65003;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      String> customtype = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        String.class,
        null);
  public static final int CUSTOMNAME_FIELD_NUMBER = 65004;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      String> customname = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        String.class,
        null);
  public static final int JSONTAG_FIELD_NUMBER = 65005;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      String> jsontag = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        String.class,
        null);
  public static final int MORETAGS_FIELD_NUMBER = 65006;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      String> moretags = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        String.class,
        null);
  public static final int CASTTYPE_FIELD_NUMBER = 65007;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      String> casttype = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        String.class,
        null);
  public static final int CASTKEY_FIELD_NUMBER = 65008;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      String> castkey = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        String.class,
        null);
  public static final int CASTVALUE_FIELD_NUMBER = 65009;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      String> castvalue = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        String.class,
        null);
  public static final int STDTIME_FIELD_NUMBER = 65010;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      Boolean> stdtime = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);
  public static final int STDDURATION_FIELD_NUMBER = 65011;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      Boolean> stdduration = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024gogoproto/gogo.proto\022\tgogoproto\032 googl" +
      "e/protobuf/descriptor.proto:;\n\023goproto_e" +
      "num_prefix\022\034.google.protobuf.EnumOptions" +
      "\030\261\344\003 \001(\010:=\n\025goproto_enum_stringer\022\034.goog" +
      "le.protobuf.EnumOptions\030\305\344\003 \001(\010:5\n\renum_" +
      "stringer\022\034.google.protobuf.EnumOptions\030\306" +
      "\344\003 \001(\010:7\n\017enum_customname\022\034.google.proto" +
      "buf.EnumOptions\030\307\344\003 \001(\t:0\n\010enumdecl\022\034.go" +
      "ogle.protobuf.EnumOptions\030\310\344\003 \001(\010:A\n\024enu" +
      "mvalue_customname\022!.google.protobuf.Enum",
      "ValueOptions\030\321\203\004 \001(\t:;\n\023goproto_getters_" +
      "all\022\034.google.protobuf.FileOptions\030\231\354\003 \001(" +
      "\010:?\n\027goproto_enum_prefix_all\022\034.google.pr" +
      "otobuf.FileOptions\030\232\354\003 \001(\010:<\n\024goproto_st" +
      "ringer_all\022\034.google.protobuf.FileOptions" +
      "\030\233\354\003 \001(\010:9\n\021verbose_equal_all\022\034.google.p" +
      "rotobuf.FileOptions\030\234\354\003 \001(\010:0\n\010face_all\022" +
      "\034.google.protobuf.FileOptions\030\235\354\003 \001(\010:4\n" +
      "\014gostring_all\022\034.google.protobuf.FileOpti" +
      "ons\030\236\354\003 \001(\010:4\n\014populate_all\022\034.google.pro",
      "tobuf.FileOptions\030\237\354\003 \001(\010:4\n\014stringer_al" +
      "l\022\034.google.protobuf.FileOptions\030\240\354\003 \001(\010:" +
      "3\n\013onlyone_all\022\034.google.protobuf.FileOpt" +
      "ions\030\241\354\003 \001(\010:1\n\tequal_all\022\034.google.proto" +
      "buf.FileOptions\030\245\354\003 \001(\010:7\n\017description_a" +
      "ll\022\034.google.protobuf.FileOptions\030\246\354\003 \001(\010" +
      ":3\n\013testgen_all\022\034.google.protobuf.FileOp" +
      "tions\030\247\354\003 \001(\010:4\n\014benchgen_all\022\034.google.p" +
      "rotobuf.FileOptions\030\250\354\003 \001(\010:5\n\rmarshaler" +
      "_all\022\034.google.protobuf.FileOptions\030\251\354\003 \001",
      "(\010:7\n\017unmarshaler_all\022\034.google.protobuf." +
      "FileOptions\030\252\354\003 \001(\010:<\n\024stable_marshaler_" +
      "all\022\034.google.protobuf.FileOptions\030\253\354\003 \001(" +
      "\010:1\n\tsizer_all\022\034.google.protobuf.FileOpt" +
      "ions\030\254\354\003 \001(\010:A\n\031goproto_enum_stringer_al" +
      "l\022\034.google.protobuf.FileOptions\030\255\354\003 \001(\010:" +
      "9\n\021enum_stringer_all\022\034.google.protobuf.F" +
      "ileOptions\030\256\354\003 \001(\010:<\n\024unsafe_marshaler_a" +
      "ll\022\034.google.protobuf.FileOptions\030\257\354\003 \001(\010" +
      ":>\n\026unsafe_unmarshaler_all\022\034.google.prot",
      "obuf.FileOptions\030\260\354\003 \001(\010:B\n\032goproto_exte" +
      "nsions_map_all\022\034.google.protobuf.FileOpt" +
      "ions\030\261\354\003 \001(\010:@\n\030goproto_unrecognized_all" +
      "\022\034.google.protobuf.FileOptions\030\262\354\003 \001(\010:8" +
      "\n\020gogoproto_import\022\034.google.protobuf.Fil" +
      "eOptions\030\263\354\003 \001(\010:6\n\016protosizer_all\022\034.goo" +
      "gle.protobuf.FileOptions\030\264\354\003 \001(\010:3\n\013comp" +
      "are_all\022\034.google.protobuf.FileOptions\030\265\354" +
      "\003 \001(\010:4\n\014typedecl_all\022\034.google.protobuf." +
      "FileOptions\030\266\354\003 \001(\010:4\n\014enumdecl_all\022\034.go",
      "ogle.protobuf.FileOptions\030\267\354\003 \001(\010::\n\017gop" +
      "roto_getters\022\037.google.protobuf.MessageOp" +
      "tions\030\201\364\003 \001(\010:;\n\020goproto_stringer\022\037.goog" +
      "le.protobuf.MessageOptions\030\203\364\003 \001(\010:8\n\rve" +
      "rbose_equal\022\037.google.protobuf.MessageOpt" +
      "ions\030\204\364\003 \001(\010:/\n\004face\022\037.google.protobuf.M" +
      "essageOptions\030\205\364\003 \001(\010:3\n\010gostring\022\037.goog" +
      "le.protobuf.MessageOptions\030\206\364\003 \001(\010:3\n\010po" +
      "pulate\022\037.google.protobuf.MessageOptions\030" +
      "\207\364\003 \001(\010:3\n\010stringer\022\037.google.protobuf.Me",
      "ssageOptions\030\300\213\004 \001(\010:2\n\007onlyone\022\037.google" +
      ".protobuf.MessageOptions\030\211\364\003 \001(\010:0\n\005equa" +
      "l\022\037.google.protobuf.MessageOptions\030\215\364\003 \001" +
      "(\010:6\n\013description\022\037.google.protobuf.Mess" +
      "ageOptions\030\216\364\003 \001(\010:2\n\007testgen\022\037.google.p" +
      "rotobuf.MessageOptions\030\217\364\003 \001(\010:3\n\010benchg" +
      "en\022\037.google.protobuf.MessageOptions\030\220\364\003 " +
      "\001(\010:4\n\tmarshaler\022\037.google.protobuf.Messa" +
      "geOptions\030\221\364\003 \001(\010:6\n\013unmarshaler\022\037.googl" +
      "e.protobuf.MessageOptions\030\222\364\003 \001(\010:;\n\020sta",
      "ble_marshaler\022\037.google.protobuf.MessageO" +
      "ptions\030\223\364\003 \001(\010:0\n\005sizer\022\037.google.protobu" +
      "f.MessageOptions\030\224\364\003 \001(\010:;\n\020unsafe_marsh" +
      "aler\022\037.google.protobuf.MessageOptions\030\227\364" +
      "\003 \001(\010:=\n\022unsafe_unmarshaler\022\037.google.pro" +
      "tobuf.MessageOptions\030\230\364\003 \001(\010:A\n\026goproto_" +
      "extensions_map\022\037.google.protobuf.Message" +
      "Options\030\231\364\003 \001(\010:?\n\024goproto_unrecognized\022" +
      "\037.google.protobuf.MessageOptions\030\232\364\003 \001(\010" +
      ":5\n\nprotosizer\022\037.google.protobuf.Message",
      "Options\030\234\364\003 \001(\010:2\n\007compare\022\037.google.prot" +
      "obuf.MessageOptions\030\235\364\003 \001(\010:3\n\010typedecl\022" +
      "\037.google.protobuf.MessageOptions\030\236\364\003 \001(\010" +
      ":1\n\010nullable\022\035.google.protobuf.FieldOpti" +
      "ons\030\351\373\003 \001(\010:.\n\005embed\022\035.google.protobuf.F" +
      "ieldOptions\030\352\373\003 \001(\010:3\n\ncustomtype\022\035.goog" +
      "le.protobuf.FieldOptions\030\353\373\003 \001(\t:3\n\ncust" +
      "omname\022\035.google.protobuf.FieldOptions\030\354\373" +
      "\003 \001(\t:0\n\007jsontag\022\035.google.protobuf.Field" +
      "Options\030\355\373\003 \001(\t:1\n\010moretags\022\035.google.pro",
      "tobuf.FieldOptions\030\356\373\003 \001(\t:1\n\010casttype\022\035" +
      ".google.protobuf.FieldOptions\030\357\373\003 \001(\t:0\n" +
      "\007castkey\022\035.google.protobuf.FieldOptions\030" +
      "\360\373\003 \001(\t:2\n\tcastvalue\022\035.google.protobuf.F" +
      "ieldOptions\030\361\373\003 \001(\t:0\n\007stdtime\022\035.google." +
      "protobuf.FieldOptions\030\362\373\003 \001(\010:4\n\013stddura" +
      "tion\022\035.google.protobuf.FieldOptions\030\363\373\003 " +
      "\001(\010B!\n\023com.google.protobufB\ncom.google.protobuf.GoGoProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
    goprotoEnumPrefix.internalInit(descriptor.getExtensions().get(0));
    goprotoEnumStringer.internalInit(descriptor.getExtensions().get(1));
    enumStringer.internalInit(descriptor.getExtensions().get(2));
    enumCustomname.internalInit(descriptor.getExtensions().get(3));
    enumdecl.internalInit(descriptor.getExtensions().get(4));
    enumvalueCustomname.internalInit(descriptor.getExtensions().get(5));
    goprotoGettersAll.internalInit(descriptor.getExtensions().get(6));
    goprotoEnumPrefixAll.internalInit(descriptor.getExtensions().get(7));
    goprotoStringerAll.internalInit(descriptor.getExtensions().get(8));
    verboseEqualAll.internalInit(descriptor.getExtensions().get(9));
    faceAll.internalInit(descriptor.getExtensions().get(10));
    gostringAll.internalInit(descriptor.getExtensions().get(11));
    populateAll.internalInit(descriptor.getExtensions().get(12));
    stringerAll.internalInit(descriptor.getExtensions().get(13));
    onlyoneAll.internalInit(descriptor.getExtensions().get(14));
    equalAll.internalInit(descriptor.getExtensions().get(15));
    descriptionAll.internalInit(descriptor.getExtensions().get(16));
    testgenAll.internalInit(descriptor.getExtensions().get(17));
    benchgenAll.internalInit(descriptor.getExtensions().get(18));
    marshalerAll.internalInit(descriptor.getExtensions().get(19));
    unmarshalerAll.internalInit(descriptor.getExtensions().get(20));
    stableMarshalerAll.internalInit(descriptor.getExtensions().get(21));
    sizerAll.internalInit(descriptor.getExtensions().get(22));
    goprotoEnumStringerAll.internalInit(descriptor.getExtensions().get(23));
    enumStringerAll.internalInit(descriptor.getExtensions().get(24));
    unsafeMarshalerAll.internalInit(descriptor.getExtensions().get(25));
    unsafeUnmarshalerAll.internalInit(descriptor.getExtensions().get(26));
    goprotoExtensionsMapAll.internalInit(descriptor.getExtensions().get(27));
    goprotoUnrecognizedAll.internalInit(descriptor.getExtensions().get(28));
    gogoprotoImport.internalInit(descriptor.getExtensions().get(29));
    protosizerAll.internalInit(descriptor.getExtensions().get(30));
    compareAll.internalInit(descriptor.getExtensions().get(31));
    typedeclAll.internalInit(descriptor.getExtensions().get(32));
    enumdeclAll.internalInit(descriptor.getExtensions().get(33));
    goprotoGetters.internalInit(descriptor.getExtensions().get(34));
    goprotoStringer.internalInit(descriptor.getExtensions().get(35));
    verboseEqual.internalInit(descriptor.getExtensions().get(36));
    face.internalInit(descriptor.getExtensions().get(37));
    gostring.internalInit(descriptor.getExtensions().get(38));
    populate.internalInit(descriptor.getExtensions().get(39));
    stringer.internalInit(descriptor.getExtensions().get(40));
    onlyone.internalInit(descriptor.getExtensions().get(41));
    equal.internalInit(descriptor.getExtensions().get(42));
    description.internalInit(descriptor.getExtensions().get(43));
    testgen.internalInit(descriptor.getExtensions().get(44));
    benchgen.internalInit(descriptor.getExtensions().get(45));
    marshaler.internalInit(descriptor.getExtensions().get(46));
    unmarshaler.internalInit(descriptor.getExtensions().get(47));
    stableMarshaler.internalInit(descriptor.getExtensions().get(48));
    sizer.internalInit(descriptor.getExtensions().get(49));
    unsafeMarshaler.internalInit(descriptor.getExtensions().get(50));
    unsafeUnmarshaler.internalInit(descriptor.getExtensions().get(51));
    goprotoExtensionsMap.internalInit(descriptor.getExtensions().get(52));
    goprotoUnrecognized.internalInit(descriptor.getExtensions().get(53));
    protosizer.internalInit(descriptor.getExtensions().get(54));
    compare.internalInit(descriptor.getExtensions().get(55));
    typedecl.internalInit(descriptor.getExtensions().get(56));
    nullable.internalInit(descriptor.getExtensions().get(57));
    embed.internalInit(descriptor.getExtensions().get(58));
    customtype.internalInit(descriptor.getExtensions().get(59));
    customname.internalInit(descriptor.getExtensions().get(60));
    jsontag.internalInit(descriptor.getExtensions().get(61));
    moretags.internalInit(descriptor.getExtensions().get(62));
    casttype.internalInit(descriptor.getExtensions().get(63));
    castkey.internalInit(descriptor.getExtensions().get(64));
    castvalue.internalInit(descriptor.getExtensions().get(65));
    stdtime.internalInit(descriptor.getExtensions().get(66));
    stdduration.internalInit(descriptor.getExtensions().get(67));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}