# AUTOGENERATED BY THE GRADLE SCRIPT. DO NOT EDIT.

require 'jar_dependencies'
require_jar('io.netty', 'netty-all', '4.1.49.Final')
require_jar('org.apache.logging.log4j', 'log4j-api', '2.11.1')
require_jar('com.google.protobuf', 'protobuf-java', '3.14.0')
require_jar('org.xerial.snappy', 'snappy-java', '1.1.8.4')
require_jar('com.fasterxml.jackson.core', 'jackson-core', '2.12.3')
require_jar('com.fasterxml.jackson.core', 'jackson-databind', '2.12.3')
require_jar('org.logstash.plugins.input.http', 'logstash-input-http', '4.0.1')
