# AUTOGENERATED BY THE GRADLE SCRIPT. DO NOT EDIT.

require 'jar_dependencies'
require_jar('io.netty', 'netty-all', '4.1.18.Final')
require_jar('io.netty', 'netty-tcnative-boringssl-static', '2.0.7.Final')
require_jar('org.apache.logging.log4j', 'log4j-api', '2.6.2')
require_jar('org.logstash.plugins.input.http', 'logstash-input-http', '3.1.0')
